/*
Estuary API

This is the API for the Estuary application.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MainGetApiKeysResp struct for MainGetApiKeysResp
type MainGetApiKeysResp struct {
	Expiry *string `json:"expiry,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewMainGetApiKeysResp instantiates a new MainGetApiKeysResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainGetApiKeysResp() *MainGetApiKeysResp {
	this := MainGetApiKeysResp{}
	return &this
}

// NewMainGetApiKeysRespWithDefaults instantiates a new MainGetApiKeysResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainGetApiKeysRespWithDefaults() *MainGetApiKeysResp {
	this := MainGetApiKeysResp{}
	return &this
}

// GetExpiry returns the Expiry field value if set, zero value otherwise.
func (o *MainGetApiKeysResp) GetExpiry() string {
	if o == nil || o.Expiry == nil {
		var ret string
		return ret
	}
	return *o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetApiKeysResp) GetExpiryOk() (*string, bool) {
	if o == nil || o.Expiry == nil {
		return nil, false
	}
	return o.Expiry, true
}

// HasExpiry returns a boolean if a field has been set.
func (o *MainGetApiKeysResp) HasExpiry() bool {
	if o != nil && o.Expiry != nil {
		return true
	}

	return false
}

// SetExpiry gets a reference to the given string and assigns it to the Expiry field.
func (o *MainGetApiKeysResp) SetExpiry(v string) {
	o.Expiry = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *MainGetApiKeysResp) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainGetApiKeysResp) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *MainGetApiKeysResp) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *MainGetApiKeysResp) SetToken(v string) {
	o.Token = &v
}

func (o MainGetApiKeysResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Expiry != nil {
		toSerialize["expiry"] = o.Expiry
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableMainGetApiKeysResp struct {
	value *MainGetApiKeysResp
	isSet bool
}

func (v NullableMainGetApiKeysResp) Get() *MainGetApiKeysResp {
	return v.value
}

func (v *NullableMainGetApiKeysResp) Set(val *MainGetApiKeysResp) {
	v.value = val
	v.isSet = true
}

func (v NullableMainGetApiKeysResp) IsSet() bool {
	return v.isSet
}

func (v *NullableMainGetApiKeysResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainGetApiKeysResp(val *MainGetApiKeysResp) *NullableMainGetApiKeysResp {
	return &NullableMainGetApiKeysResp{value: val, isSet: true}
}

func (v NullableMainGetApiKeysResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainGetApiKeysResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


