/*
Estuary API

This is the API for the Estuary application.

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MainCreateCollectionBody struct for MainCreateCollectionBody
type MainCreateCollectionBody struct {
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewMainCreateCollectionBody instantiates a new MainCreateCollectionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainCreateCollectionBody() *MainCreateCollectionBody {
	this := MainCreateCollectionBody{}
	return &this
}

// NewMainCreateCollectionBodyWithDefaults instantiates a new MainCreateCollectionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainCreateCollectionBodyWithDefaults() *MainCreateCollectionBody {
	this := MainCreateCollectionBody{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MainCreateCollectionBody) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainCreateCollectionBody) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MainCreateCollectionBody) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MainCreateCollectionBody) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MainCreateCollectionBody) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainCreateCollectionBody) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MainCreateCollectionBody) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MainCreateCollectionBody) SetName(v string) {
	o.Name = &v
}

func (o MainCreateCollectionBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableMainCreateCollectionBody struct {
	value *MainCreateCollectionBody
	isSet bool
}

func (v NullableMainCreateCollectionBody) Get() *MainCreateCollectionBody {
	return v.value
}

func (v *NullableMainCreateCollectionBody) Set(val *MainCreateCollectionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMainCreateCollectionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMainCreateCollectionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainCreateCollectionBody(val *MainCreateCollectionBody) *NullableMainCreateCollectionBody {
	return &NullableMainCreateCollectionBody{value: val, isSet: true}
}

func (v NullableMainCreateCollectionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainCreateCollectionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


